on: 
  workflow_dispatch:
    
name: Azure ARM via Bicep
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.MercuryHealthGitHubActionsSP }}

    - name: where are we
      run: |
        pwd
        ls -la

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: blizzBicep-rg 
        template: ./templates/web-app-sql-database/azuredeploy.bicep
        parameters: storagePrefix=blizzstore
        #template: ./azuredeploy.bicep
